version: "3.8"
services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 25672:25672
      - 15672:15672
      - 15692:15692
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
